### ISSUE TITLE
Tabix headers

### ISSUE THREAD

**Issue by bschilder** [eQTL-Catalogue/eQTL-Catalogue-resources#1]
Hi there, 

Thanks so much for creating this amazing resource! One thing I couldn't seem to find was the header names for the tabix files. 

I tried to include the header with the ` -h` / `--print-header` flag, but it didn't return the column names.
```
tabix --print-header ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_naive.all.tsv.gz 12:40114781-41114084 | head
```

I also tried pulling just the header with the `-H` flag, but nothing was returned:
```
tabix -H ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_naive.all.tsv.gz
```

If the names aren't included in the file itself, could you list them in the documentation somewhere?

Many thanks, 
Brian Schilder
Bioinformatician 
Icahn School of Medicine

**Comment by kauralasoo** [comment]
Dear Brian,

Thanks for reporting this. All of the tsv files have headers, but I think that our tabix indices might be unaware of them. However, you should be able to get them with curl, e.g. something like this should work:

```
curl -s ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/ge/Alasoo_2018_ge_macrophage_naive.all.tsv.gz | zcat | head -n 1
```

Since the header is the same for all files at the moment, you should only have to do it once. To find out what the columns are, have a look at our [API documentation](https://www.ebi.ac.uk/eqtl/api-docs/) (Section Available data fields)

Best,
Kaur

Btw, the best way to contact us is at eqtlcatalogue@ebi.ac.uk, the email will then go to all of the developers.

**Comment by bschilder** [comment]
Perfect, thank you so much! Just tried this and it worked.

Thanks,
Brian

Brian M. Schilder

Bioinformatician II

Department of Neuroscience

Department of Genetics & Genomic Sciences

Ronald M. Loeb Center for Alzheimer's Disease

The Icahn School of Medicine at Mount Sinai

New York City, NY 10029

LinkedIn <https://www.linkedin.com/in/brian-schilder/>  |  ResearchGate
<https://www.researchgate.net/profile/Brian_Schilder>  |  Professional
Website <https://bschilder.github.io/BMSchilder>
