### ISSUE TITLE
Tabix Issue For Accessing Specific Regions in the Files

### ISSUE THREAD

**Issue by maegsul** [eQTL-Catalogue/eQTL-Catalogue-resources#15]
Hi, lately I am having problems with accessing specific regions in the eQTL Catalogue files using tabix. For instance, the example code given in https://www.ebi.ac.uk/eqtl/Data_access/ : 

`tabix ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_monocyte.all.tsv.gz 20:46120612-46120613
`
...doesn't work for me anymore (I am using the most recent tabix, v1.13) :

> [E::hts_open_format] Failed to open file "ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_monocyte.all.tsv.gz" : Connection reset by peer
> Couldn't open "ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_monocyte.all.tsv.gz": Connection reset by peer

Is there a work around for this? I thought maybe there is a problem on my side, but when I tried other FTP servers other than EBI (such as ftp://ftp.broadinstitute.org/), these worked unexpectedly. And oddly enough, I can download  ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_monocyte.all.tsv.gz via Google Chrome browser download but not with `wget`, for instance. Do you have similar problems lately?

By the way, from time to time, when I try with http (but not with https), it also works:

`tabix http://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_monocyte.all.tsv.gz 20:46120612-46120613
`

Thanks once again for this amazing source for the community and thank you in advance for your help!

**Comment by kauralasoo** [comment]
Hi Fahri,

This tabix command works for me right now, but we do see occasional intermittent connection issues with the EBI ftp server. If you need to make a lot of tabix queries, you might want to download the full tsv files and run tabix locally. If you can afford the disk space, then this is likely to be much faster and you do not have to do error handling and retries. We have now added md5sum.txt files to all of the subfolders in the FTP so that you can check that the downloaded files are intact.

Other option is that there are too many requests from the same IP address (e.g. shared computing facility at your university) then EBI might temporarily block these requests. It is likely that your Google Chrome browser is using a different IP address from the wget command that you are executing on the server.

Btw, I would normally use ftp instead of http/https, e.g.:
tabix -f ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/BLUEPRINT/ge/BLUEPRINT_ge_monocyte.all.tsv.gz 20:46120612-46120613

In this case the -f flag is necessary, because the index files appears to be older than the tsv file.

Best,
Kaur

**Comment by maegsul** [comment]
Hi Kaur, Thanks a lot for your reply. Indeed, it seems like probably my IP address on the server was blocked possibly because of many requests at a time. I will try again later then, and update this issue if there will be any updates.
